service: foo

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}

functions:
  foo:
    handler: index.handler
